language: python
python:
  - "2.7"
  - "3.6"

install: 
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run -m shakecastaebm.tests.bundle

branches:
  only:
    - master

after_success:
  - codecov